-- AUTO-GENERATED by Data Contract Architect (Phase 14)
-- design_id : afc15fcb-157e-4c5f-9fe4-08f8e36ac2b8
-- client    : aetna
-- generated : 2026-04-30T21:27:32.639706+00:00
-- DO NOT EDIT BY HAND. Re-approve the design from the UI to
-- regenerate this file. The runtime substitutes {schema} with
-- the per-tenant Bronze schema (e.g. BRONZE_AETNA).

CREATE TABLE {schema}.RAW_CLAIMS (

  claim_id VARCHAR NOT NULL,
  member_id VARCHAR NOT NULL,
  provider_npi VARCHAR NOT NULL,
  cpt_code VARCHAR NOT NULL,
  icd10_primary VARCHAR,
  icd10_secondary VARCHAR,
  service_date DATE NOT NULL,
  billed_amount DECIMAL(12, 2) NOT NULL,
  claim_status VARCHAR,
  plan_id VARCHAR,
  prior_auth_ref VARCHAR,
  PRIMARY KEY (claim_id),
    -- Mandatory DataLink audit columns (Phase 14 architect inject)
    _load_dt           TIMESTAMP,
    _source_file       VARCHAR,
    _batch_id          VARCHAR,
    _record_source     VARCHAR,
    _load_type         VARCHAR,
    _file_row_number   BIGINT,
    _record_hash       VARCHAR
);
