-- AUTO-GENERATED by Pipeline Architect (Phase 15)
-- Bronze DDL (with _extra) for aetna / membership
-- instance_id : 6d296c91-e2a6-4ea7-b306-422db85697cd
-- generated   : 2026-05-10T00:19:17.979727+00:00
-- DO NOT EDIT BY HAND. Re-deploy from the UI to regenerate.

-- Phase 15.7 Pipeline Architect — Bronze landing for aetna / membership
-- Generated from CONTROL.global_bronze_catalog_fields
-- Generated at: 2026-05-10T00:17:22.205429+00:00
-- Phase 16.1 — All business columns NULLABLE (Bronze is raw landing).
CREATE TABLE IF NOT EXISTS BRONZE_AETNA.raw_membership (
    -- ── Bronze business columns (NULL-permissive) ──
    payer_name                         VARCHAR        NULL,  -- [PII]
    member_card_id                     VARCHAR        NULL,  -- [BK]
    member_medicare_id                 VARCHAR        NULL,  -- [PHI] [BK]
    member_medicaid_id                 VARCHAR        NULL,  -- [PHI] [BK]
    member_first_name                  VARCHAR        NULL,  -- [PII]
    member_middle_name                 VARCHAR        NULL,  -- [PII]
    member_last_name                   VARCHAR        NULL,  -- [PII]
    member_gender                      VARCHAR        NULL,
    member_birth_date                  DATE           NULL,  -- [PII]
    member_phone                       VARCHAR        NULL,  -- [PII]
    member_street_address_line1        VARCHAR        NULL,  -- [PII]
    member_street_address_line2        VARCHAR        NULL,  -- [PII]
    member_county_code                 VARCHAR        NULL,  -- [PII]
    member_county_name                 VARCHAR        NULL,  -- [PII]
    member_city                        VARCHAR        NULL,  -- [PII]
    member_state                       VARCHAR        NULL,  -- [PII]
    member_zip_code                    VARCHAR        NULL,  -- [PII]
    member_active_status               VARCHAR        NULL,
    member_relationship_code           VARCHAR        NULL,
    member_medicaid_indicator          BOOLEAN        NULL,  -- [PHI]
    member_medicaid_dual_eligibility_indicator BOOLEAN        NULL,  -- [PHI]
    member_dual_eligibility_begin_date DATE           NULL,
    member_dual_eligibility_end_date   DATE           NULL,
    member_coverage_effective_date     DATE           NULL,  -- [PHI]
    member_coverage_end_date           DATE           NULL,  -- [PHI]
    member_provider_pcp_begin_date     DATE           NULL,
    member_health_plan_begin_date      DATE           NULL,  -- [PHI]
    member_enrollment_date             DATE           NULL,
    member_line_of_business            VARCHAR        NULL,
    member_product                     VARCHAR        NULL,
    product_description                VARCHAR        NULL,
    plan_benenfit_package_id           INTEGER        NULL,  -- [PHI]
    plan_benefit_package_name          VARCHAR        NULL,  -- [PII] [PHI]
    segment_id_plan_benefit_package    INTEGER        NULL,  -- [PHI]
    member_product_begin_date          DATE           NULL,
    managed_care_organization_contract_number VARCHAR        NULL,  -- [PHI]
    attributed_provider_id             VARCHAR        NULL,  -- [PHI] [BK]
    atrributed_provider_npi            VARCHAR        NULL,  -- [PHI]
    attributed_provider_contract_id    DECIMAL(20, 4) NULL,
    plan_benefit_package_id            VARCHAR        NULL,  -- [PHI]
    refresh_date                       DATE           NULL,
    -- ── Phase 15.7 variant overflow (any column not in agreed contract) ──
    _extra                             VARIANT        NULL,  -- Phase 17.2 — JSON of vendor columns not in canonical Bronze catalog. Auto-populated by COPY INTO. Propagates to Silver Sat._extensions.
    -- ── Standard Bronze audit columns ──
    _load_dt                           TIMESTAMP      NULL,
    _source_file                       VARCHAR        NULL,
    _batch_id                          VARCHAR        NULL,
    _record_source                     VARCHAR        NULL,
    _load_type                         VARCHAR        NULL,
    _file_row_number                   BIGINT         NULL,
    _record_hash                       VARCHAR        NULL
);
