-- AUTO-GENERATED by Pipeline Architect (Phase 15)
-- Bronze DDL (with _extra) for aetna / provider
-- instance_id : df4b104b-7f8e-482c-ac9a-310065a3df4c
-- generated   : 2026-05-10T00:20:16.101456+00:00
-- DO NOT EDIT BY HAND. Re-deploy from the UI to regenerate.

-- Phase 15.7 Pipeline Architect — Bronze landing for aetna / provider
-- Generated from CONTROL.global_bronze_catalog_fields
-- Generated at: 2026-05-10T00:19:55.310538+00:00
-- Phase 16.1 — All business columns NULLABLE (Bronze is raw landing).
CREATE TABLE IF NOT EXISTS BRONZE_AETNA.raw_provider (
    -- ── Bronze business columns (NULL-permissive) ──
    national_provider_identifier_npi   VARCHAR        NULL,  -- [PHI]
    provider_identification_number_id  VARCHAR        NULL,
    provider_first_name                VARCHAR        NULL,  -- [PII]
    provider_middle_name               VARCHAR        NULL,  -- [PII]
    provider_last_name                 VARCHAR        NULL,  -- [PII]
    provider_tax_id                    VARCHAR        NULL,  -- [PII]
    provider_tax_id_name               VARCHAR        NULL,  -- [PII] [PHI]
    provider_primary_servicing_address_line_1 VARCHAR        NULL,  -- [PII]
    provider_primary_servicing_address_line_2 VARCHAR        NULL,  -- [PII]
    provider_primary_servicing_address_city VARCHAR        NULL,  -- [PII]
    provider_primary_servicing_address_state VARCHAR        NULL,  -- [PII]
    provider_primary_servicing_address_zip_code VARCHAR        NULL,  -- [PII]
    provider_contracted_entity_name    VARCHAR        NULL,  -- [PII]
    refresh_date                       DATE           NULL,
    -- ── Phase 15.7 variant overflow (any column not in agreed contract) ──
    _extra                             VARIANT        NULL,  -- Phase 17.2 — JSON of vendor columns not in canonical Bronze catalog. Auto-populated by COPY INTO. Propagates to Silver Sat._extensions.
    -- ── Standard Bronze audit columns ──
    _load_dt                           TIMESTAMP      NULL,
    _source_file                       VARCHAR        NULL,
    _batch_id                          VARCHAR        NULL,
    _record_source                     VARCHAR        NULL,
    _load_type                         VARCHAR        NULL,
    _file_row_number                   BIGINT         NULL,
    _record_hash                       VARCHAR        NULL
);
