-- AUTO-GENERATED by Data Contract Architect (Phase 14)
-- design_id : f1684f79-b208-48dc-aeba-56ec244e6e4b
-- client    : aetna
-- generated : 2026-04-30T21:36:41.503487+00:00
-- DO NOT EDIT BY HAND. Re-approve the design from the UI to
-- regenerate this file. The runtime substitutes {schema} with
-- the per-tenant Bronze schema (e.g. BRONZE_AETNA).

CREATE TABLE {schema}.RAW_CLAIMS (
  claim_id VARCHAR NOT NULL,
  member_id VARCHAR NOT NULL,
  provider_npi VARCHAR,
  cpt_code VARCHAR,
  icd10_primary VARCHAR,
  _load_dt TIMESTAMP NOT NULL,
  _source_file VARCHAR NOT NULL,
  _batch_id VARCHAR NOT NULL,
  _record_source VARCHAR NOT NULL,
  _load_type VARCHAR NOT NULL,
  _file_row_number INTEGER NOT NULL,
  _record_hash VARCHAR NOT NULL,
  PRIMARY KEY (claim_id, member_id, _load_dt)
);
