-- AUTO-GENERATED by Pipeline Architect (Phase 15)
-- Bronze DDL (with _variant_overflow) for aetna / membership
-- instance_id : 797ba252-d748-4869-b7ea-c921e7ae29be
-- generated   : 2026-05-03T02:53:39.733705+00:00
-- DO NOT EDIT BY HAND. Re-deploy from the UI to regenerate.

-- Phase 15.7 Pipeline Architect — Bronze landing for aetna / membership
-- Generated from CONTROL.global_bronze_catalog_fields
-- Generated at: 2026-05-03T02:51:52.806898+00:00
CREATE TABLE IF NOT EXISTS BRONZE_AETNA.raw_membership (
    payer_name                       VARCHAR        NOT NULL  -- [PII],
    member_card_id                   VARCHAR        NOT NULL  -- [BK],
    member_medicare_id               VARCHAR        NOT NULL  -- [PHI] [BK],
    member_medicaid_id               VARCHAR        NOT NULL  -- [PHI] [BK],
    member_first_name                VARCHAR        NOT NULL  -- [PII],
    member_middle_name               VARCHAR        NOT NULL  -- [PII],
    member_last_name                 VARCHAR        NOT NULL  -- [PII],
    member_gender                    VARCHAR        NOT NULL,
    member_birth_date                DATE           NOT NULL  -- [PII],
    member_phone                     VARCHAR        NOT NULL  -- [PII],
    member_street_address_line1      VARCHAR        NOT NULL  -- [PII],
    member_street_address_line2      VARCHAR        NULL  -- [PII],
    member_county_code               VARCHAR        NULL  -- [PII],
    member_county_name               VARCHAR        NULL  -- [PII],
    member_city                      VARCHAR        NOT NULL  -- [PII],
    member_state                     VARCHAR        NOT NULL  -- [PII],
    member_zip_code                  VARCHAR        NOT NULL  -- [PII],
    member_active_status             VARCHAR        NOT NULL,
    member_relationship_code         VARCHAR        NOT NULL,
    member_medicaid_indicator        BOOLEAN        NOT NULL  -- [PHI],
    member_medicaid_dual_eligibility_indicator BOOLEAN        NOT NULL  -- [PHI],
    member_dual_eligibility_begin_date DATE           NOT NULL,
    member_dual_eligibility_end_date DATE           NOT NULL,
    member_coverage_effective_date   DATE           NOT NULL  -- [PHI],
    member_coverage_end_date         DATE           NOT NULL  -- [PHI],
    member_provider_pcp_begin_date   DATE           NOT NULL,
    member_health_plan_begin_date    DATE           NOT NULL  -- [PHI],
    member_enrollment_date           DATE           NULL,
    member_line_of_business          VARCHAR        NOT NULL,
    member_product                   VARCHAR        NOT NULL,
    product_description              VARCHAR        NULL,
    plan_benenfit_package_id         INTEGER        NOT NULL  -- [PHI],
    plan_benefit_package_name        VARCHAR        NOT NULL  -- [PII] [PHI],
    segment_id_plan_benefit_package  INTEGER        NULL  -- [PHI],
    member_product_begin_date        DATE           NOT NULL,
    managed_care_organization_contract_number VARCHAR        NOT NULL  -- [PHI],
    attributed_provider_id           VARCHAR        NOT NULL  -- [PHI] [BK],
    atrributed_provider_npi          VARCHAR        NOT NULL  -- [PHI],
    attributed_provider_contract_id  DECIMAL(20, 4) NOT NULL,
    plan_benefit_package_id          VARCHAR        NOT NULL  -- [PHI],
    refresh_date                     DATE           NOT NULL,
    -- ── Phase 15.7 variant overflow (any column not in the agreed contract lands here) ──,
    _variant_overflow                VARIANT        NULL  -- JSON of unexpected columns; never propagates to Silver/Gold without HITL handshake,
    -- ── Standard Bronze audit columns ──,
    _load_dt                         TIMESTAMP,
    _source_file                     VARCHAR,
    _batch_id                        VARCHAR,
    _record_source                   VARCHAR,
    _load_type                       VARCHAR,
    _file_row_number                 BIGINT,
    _record_hash                     VARCHAR
);
