"""Demo-state wipe — Phase 22.

Single function ``wipe_everything()`` that nukes ALL workflow-driving data
across Snowflake + PostgreSQL + SQL Server in one transaction-like sequence,
returning a structured report the UI can render.

What it WIPES (workflow data):
  * Snowflake CONTROL.* — every table that drives the pipeline workflow:
      - global_bronze_catalog_datasets + fields (the 33-dataset seed)
      - global_silver_schema_* (datasets + tables + columns)
      - global_gold_schema_* (datasets + fields)
      - all *_mappings, *_audit_log, client_*, pipeline_*, dq_*, gx_*,
        agent_proposals, version_history, schema_drift_events …
  * Snowflake per-client schemas — BRONZE_<client> / SILVER_<client> /
    GOLD_<client> dropped CASCADE
  * PostgreSQL operational DB — all data tables in the configured database
  * SQL Server operational DB — same
  * Filesystem — auto-generated DAG factories, dbt models, DDL files,
    generated data files
  * Airflow metadata — task_instance / dag_run / xcom / log

What it KEEPS (infrastructure):
  * Snowflake account, warehouse, role, database (DATALINK_DEV), CONTROL
    schema definition (tables empty but exist)
  * The 6 industry-standard RAG chunks in standard_registry (10 min to
    reload via Voyage; user can flag `--include-standards` to drop them
    too)
  * Postgres / SQL Server / Airflow infra containers (still running)
  * .env, API keys, dbt profiles
  * Docker compose stack

This is "factory reset to pre-`load_product_catalog` state" — exactly what
the user described as "nothing that drives workflow is concerned".
"""

from __future__ import annotations

import os
import shutil
import subprocess
from dataclasses import dataclass, field
from datetime import datetime
from pathlib import Path

from datalink.admin.reset import (
    DESIGN_REGISTRY_TABLES,
    PIPELINE_DATA_TABLES,
    _log_audit,
    _now,
    _wh,
    reset_airflow_metadata,
)
from datalink.config.loader import load_settings
from datalink.logging import get_logger
from datalink.quality.control import CONTROL_SCHEMA

_log = get_logger(__name__)

REPO_ROOT = Path(os.environ.get("DL_REPO_ROOT", "/opt/datalink"))

# ---------------------------------------------------------------------------
# Tables to wipe — grouped by concern so we can compose
# ---------------------------------------------------------------------------

CATALOG_TABLES = [
    # The 33-dataset seed itself.  When wiped, DMD shows 0 datasets,
    # exactly as the user demoes.
    "global_bronze_catalog_fields",
    "global_bronze_catalog_datasets",
    "onprem_routing_rules",
    "dataset_product_lines",  # Phase 22 — per-dataset product-line junction
]

DQ_TABLES = [
    "gx_validation_results",
    "gx_failed_rows",
    "dq_validation_runs",
    "dq_suite_audit_log",
    "dq_suites",
    "schema_drift_log",  # real table per control.py:465
    "schema_drift_events",  # legacy name — kept for back-compat (silent no-op if absent)
    "anomaly_events",  # generic anomaly stream (drift / DQ-fail / orphan)
]

PROPOSAL_TABLES = [
    "proposal_tag_assignments",
    "proposal_tags",  # the tag vocabulary itself (regenerated by migration)
    "agent_proposals",
    "agent_reasoning_log",
    "agent_memory_records",
    # Phase 23 — BIMA (Bronze Inbound Mapping Agent) HITL proposals
    "bronze_inbound_field_proposals",
    "bronze_inbound_mapping_proposals",
    # Phase 23 — Canonical extension proposals (Pass 5 feedback loop)
    "bronze_canonical_extension_proposals",
]

VERSIONING_TABLES = [
    "version_tag_assignments",
    "version_history",
    "upstream_update_notifications",
    "gold_schema_audit_log",
    "silver_schema_audit_log",
    "global_silver_schema_audit_log",
    "pipeline_instance_audit_log",
    "pipeline_control_audit_log",
    "admin_reset_audit_log",  # audit log of wipe ops themselves — wiped for clean demo
    "bronze_inbound_mapping_audit",  # Phase 23 — BIMA action audit
]

CLIENT_RUNTIME_TABLES = [
    "dataset_pipeline_runs",
    "pipeline_checkpoints",
    "pipeline_task_progress",
    "pipeline_control_state",
    "pipeline_control_policies",
    "client_gold_subscriptions",
    "client_field_overrides",
    "client_routing_overrides",
    "client_pipeline_instances",
    "global_pipeline_templates",
    "pipeline_templates",
    "silver_pattern_recommendations",
    "bronze_overflow_log",
    "greenfield_dataset_proposals",
    # Phase 23 — BIMA approved/LIVE mappings (per-client field-mapping records)
    "bronze_inbound_field_mappings",
    "bronze_inbound_mappings",
    # Phase 16.7 + late-arriving artifacts — May 2026 audit gap fix
    "global_artifact_blobs",
    "global_migration_plans",
    "batch_quarantine",
    "bronze_retention_log",
    "egress_batch_log",
]

# Contracts + mapping-workflow state + custom standards.  Added May 2026
# after a full CONTROL audit found these were created by migrations but
# never wiped between demos.  All-empty today; would leak as soon as the
# first contract / mapping session / custom standard was authored.
CONTRACT_AND_MAPPING_TABLES = [
    "contract_designs",
    "contract_design_audit_log",
    "source_schema_contracts",
    "mapping_artifacts",
    "mapping_sessions",
    "mapping_session_audit_log",
    "policy_audit_log",
    "custom_standards_registry",
]

# Order matters: child tables before parent (FK-ish).  Snowflake doesn't
# enforce FKs but for readability we still wipe leaves first.
WIPE_ORDER: list[tuple[str, list[str]]] = [
    ("dq", DQ_TABLES),
    ("proposals", PROPOSAL_TABLES),
    ("versioning_audit", VERSIONING_TABLES),
    ("client_runtime", CLIENT_RUNTIME_TABLES),
    ("contracts_and_mapping", CONTRACT_AND_MAPPING_TABLES),
    ("pipeline_data", PIPELINE_DATA_TABLES),
    ("design_registry", DESIGN_REGISTRY_TABLES),
    ("bronze_catalog", CATALOG_TABLES),
]


# ---------------------------------------------------------------------------
# Report
# ---------------------------------------------------------------------------


@dataclass
class WipeReport:
    """Aggregated outcome of a wipe.  ``sections`` is keyed by what was
    wiped (snowflake / postgres / sqlserver / files / airflow) and each
    value carries success-counts + warnings."""

    actor: str
    started_at: datetime
    finished_at: datetime | None = None
    sections: dict[str, dict] = field(default_factory=dict)

    @property
    def succeeded(self) -> bool:
        return all(not s.get("errors") for s in self.sections.values())

    def total_counts(self) -> dict[str, int]:
        agg: dict[str, int] = {}
        for s in self.sections.values():
            for k, v in s.get("counts", {}).items():
                agg[k] = agg.get(k, 0) + int(v)
        return agg

    def summary_line(self) -> str:
        counts = self.total_counts()
        parts = [f"{k}={v}" for k, v in counts.items() if v]
        ok = "✅" if self.succeeded else "⚠️"
        return f"{ok} wipe_everything · " + (" · ".join(parts) if parts else "no-op")


# ---------------------------------------------------------------------------
# Snowflake wipe
# ---------------------------------------------------------------------------


def _wipe_snowflake(actor: str) -> dict:
    """Truncate every workflow-driving table in CONTROL + drop per-client schemas.

    Per-client schemas are dropped via TWO complementary paths:

      Path 1 — Snapshot drop: read CONTROL.client_pipeline_instances BEFORE
      truncating it, then DROP each (BRONZE|SILVER|GOLD)_<CLIENT>.  This is
      the "polite" path that uses our own metadata.

      Path 2 — Defensive sweep: SHOW SCHEMAS IN DATABASE DATALINK_DEV and
      drop every schema whose name starts with BRONZE_, SILVER_, or GOLD_
      regardless of whether CONTROL knows about it.  This catches:
        * orphan schemas from a Pipeline-Architect deploy that crashed
          after CREATE SCHEMA but before the CONTROL.client_pipeline_instances
          row landed
        * schemas a developer created manually outside the app
        * schemas surviving from a previous CONTROL wipe that left
          physical objects behind

    Both run every time.  Path 2 is the "100% scratch state" guarantee.
    """
    out: dict = {
        "counts": {"tables": 0, "schemas_dropped": 0, "schemas_dropped_orphan": 0},
        "warnings": [],
        "errors": [],
    }
    wh = _wh()

    # Snapshot which clients had per-layer physical schemas BEFORE we wipe
    # client_pipeline_instances.  Otherwise we lose the list.
    client_ids: set[str] = set()
    try:
        for r in wh.query(
            f"SELECT DISTINCT client_id FROM {CONTROL_SCHEMA}.client_pipeline_instances "
            f"WHERE client_id IS NOT NULL"
        ):
            cid = str(r.get("client_id") or "").strip()
            if cid:
                client_ids.add(cid)
    except Exception as exc:
        out["warnings"].append(f"client snapshot: {str(exc)[:120]}")

    # Truncate tables in order
    for section_name, tables in WIPE_ORDER:
        for tbl in tables:
            try:
                wh.execute(f"DELETE FROM {CONTROL_SCHEMA}.{tbl}")
                out["counts"]["tables"] += 1
            except Exception as exc:
                msg = str(exc)
                if "does not exist" in msg or "not authorized" in msg:
                    # Table never existed — fine
                    continue
                out["warnings"].append(f"{section_name}/{tbl}: {msg[:120]}")

    # Path 1 — Snapshot drop (clients we knew about via CONTROL)
    schemas_already_dropped: set[str] = set()
    for cid in sorted(client_ids):
        for prefix in ("BRONZE", "SILVER", "GOLD"):
            schema = f"{prefix}_{cid.upper()}"
            try:
                wh.execute(f"DROP SCHEMA IF EXISTS DATALINK_DEV.{schema} CASCADE")
                out["counts"]["schemas_dropped"] += 1
                schemas_already_dropped.add(schema.upper())
            except Exception as exc:
                out["warnings"].append(f"DROP {schema}: {str(exc)[:120]}")

    # Path 2 — Defensive sweep (catch orphans CONTROL doesn't know about)
    # Use SHOW SCHEMAS + Python filter rather than LIKE (avoids underscore-
    # escaping headaches in Snowflake LIKE patterns).  Whitelisted prefixes
    # only — never touch CONTROL, PUBLIC, INFORMATION_SCHEMA, or anything
    # else that doesn't look like a per-client medallion schema.
    SAFE_PREFIXES = ("BRONZE_", "SILVER_", "GOLD_")
    NEVER_DROP = {"CONTROL", "PUBLIC", "INFORMATION_SCHEMA"}
    try:
        all_schemas = list(wh.query("SHOW SCHEMAS IN DATABASE DATALINK_DEV"))
        candidates: list[str] = []
        for s in all_schemas:
            nm = str(s.get("name") or s.get("NAME") or "").upper().strip()
            if not nm or nm in NEVER_DROP:
                continue
            if not nm.startswith(SAFE_PREFIXES):
                continue
            if nm in schemas_already_dropped:
                continue  # already nuked via Path 1
            candidates.append(nm)
        for schema in candidates:
            try:
                wh.execute(f"DROP SCHEMA IF EXISTS DATALINK_DEV.{schema} CASCADE")
                out["counts"]["schemas_dropped_orphan"] += 1
            except Exception as exc:
                out["warnings"].append(f"orphan DROP {schema}: {str(exc)[:120]}")
    except Exception as exc:
        out["warnings"].append(f"defensive schema sweep: {str(exc)[:120]}")

    return out


# ---------------------------------------------------------------------------
# Postgres + SQL Server wipe (data tables only, NOT system tables)
# ---------------------------------------------------------------------------


def _wipe_postgres(actor: str) -> dict:
    """TRUNCATE every non-system table in the operational Postgres DB.

    Uses information_schema to discover tables.  Skips pg_catalog/information_schema.
    """
    out: dict = {"counts": {"tables": 0}, "warnings": [], "errors": []}
    try:
        import psycopg
    except ImportError as exc:
        out["errors"].append(f"psycopg not installed: {exc}")
        return out

    try:
        cfg = load_settings(env=os.environ.get("DL_ENV", "dev"))
        # Find the postgres operational DB config — there may be multiple
        pg_target = None
        for name, dbcfg in (cfg.adapters.operational_dbs or {}).items():
            kind = getattr(dbcfg, "kind", "") or getattr(dbcfg, "type", "")
            if str(kind).lower().startswith("postgres") or "postgres" in name.lower():
                pg_target = dbcfg
                break
        if pg_target is None:
            out["warnings"].append("no postgres operational_db configured — skipped")
            return out

        with psycopg.connect(
            host=pg_target.host,
            port=pg_target.port,
            user=pg_target.user,
            password=pg_target.password,
            dbname=pg_target.database,
            autocommit=True,
            connect_timeout=5,
        ) as conn:
            with conn.cursor() as cur:
                cur.execute(
                    "SELECT table_schema, table_name FROM information_schema.tables "
                    "WHERE table_type = 'BASE TABLE' "
                    "AND table_schema NOT IN ('pg_catalog', 'information_schema') "
                    "AND table_schema NOT LIKE 'pg_%'"
                )
                tables = cur.fetchall()
                for schema, tbl in tables:
                    try:
                        cur.execute(f'TRUNCATE TABLE "{schema}"."{tbl}" RESTART IDENTITY CASCADE')
                        out["counts"]["tables"] += 1
                    except Exception as exc:
                        out["warnings"].append(f"{schema}.{tbl}: {str(exc)[:120]}")
    except Exception as exc:
        out["errors"].append(f"postgres connect: {str(exc)[:200]}")
    return out


def _wipe_sqlserver(actor: str) -> dict:
    """TRUNCATE every user table in the operational SQL Server DB.

    Skips system tables.  Uses sys.tables.
    """
    out: dict = {"counts": {"tables": 0}, "warnings": [], "errors": []}
    try:
        import pyodbc
    except ImportError:
        out["warnings"].append("pyodbc not installed — sql server wipe skipped")
        return out

    try:
        cfg = load_settings(env=os.environ.get("DL_ENV", "dev"))
        ss_target = None
        for name, dbcfg in (cfg.adapters.operational_dbs or {}).items():
            kind = getattr(dbcfg, "kind", "") or getattr(dbcfg, "type", "")
            if str(kind).lower().startswith("sqlserver") or "sqlserver" in name.lower():
                ss_target = dbcfg
                break
        if ss_target is None:
            out["warnings"].append("no sqlserver operational_db configured — skipped")
            return out

        conn_str = (
            f"DRIVER={{ODBC Driver 18 for SQL Server}};"
            f"SERVER={ss_target.host},{ss_target.port};"
            f"DATABASE={ss_target.database};"
            f"UID={ss_target.user};PWD={ss_target.password};"
            f"TrustServerCertificate=yes;Encrypt=yes;Connection Timeout=5"
        )
        with pyodbc.connect(conn_str, autocommit=True) as conn:
            cur = conn.cursor()
            cur.execute(
                "SELECT SCHEMA_NAME(schema_id), name FROM sys.tables " "WHERE is_ms_shipped = 0"
            )
            tables = cur.fetchall()
            # SQL Server: TRUNCATE refuses on FK-referenced tables.  Use DELETE.
            for schema, tbl in tables:
                try:
                    cur.execute(f"DELETE FROM [{schema}].[{tbl}]")
                    out["counts"]["tables"] += 1
                except Exception as exc:
                    out["warnings"].append(f"{schema}.{tbl}: {str(exc)[:120]}")
    except Exception as exc:
        # Connection refused is the common one when SQL Server container is
        # down.  Treat as a warning, not a hard error — wipe continues.
        out["warnings"].append(f"sqlserver: {str(exc)[:200]}")
    return out


# ---------------------------------------------------------------------------
# Filesystem wipe — auto-generated DAGs / dbt / DDL / data files
# ---------------------------------------------------------------------------


def _wipe_generated_files(actor: str) -> dict:
    """Remove dags/_factory_*.py, dbt/models/{silver,gold}/<client>/,
    datalink/pipeline/{bronze,gold}/ddl/<client>_*.sql, data/generated/<client>/.
    """
    out: dict = {"counts": {"files": 0, "dirs": 0}, "warnings": [], "errors": []}

    # Factory files — except _factory_common.py
    dags_dir = REPO_ROOT / "dags"
    if dags_dir.exists():
        for p in dags_dir.glob("_factory_*.py"):
            if p.name == "_factory_common.py":
                continue
            try:
                p.unlink()
                out["counts"]["files"] += 1
            except Exception as exc:
                out["warnings"].append(f"unlink {p.name}: {str(exc)[:80]}")

    # Per-client dbt + generated dirs — discover by listing
    for parent in [
        REPO_ROOT / "dbt" / "models" / "silver",
        REPO_ROOT / "dbt" / "models" / "gold",
        REPO_ROOT / "data" / "generated",
    ]:
        if not parent.exists():
            continue
        for child in parent.iterdir():
            if not child.is_dir():
                continue
            # Skip _shared / _common style dirs
            if child.name.startswith("_") or child.name in ("common", "shared"):
                continue
            try:
                shutil.rmtree(child)
                out["counts"]["dirs"] += 1
            except PermissionError:
                # Root-owned (Airflow writes as root inside container).
                # Fall back to docker exec.
                try:
                    container_path = str(child).replace(str(REPO_ROOT), "/opt/datalink")
                    subprocess.run(
                        [
                            "docker",
                            "exec",
                            "--user",
                            "root",
                            "datalink-airflow-scheduler",
                            "rm",
                            "-rf",
                            container_path,
                        ],
                        capture_output=True,
                        text=True,
                        timeout=30,
                    )
                    if not child.exists():
                        out["counts"]["dirs"] += 1
                    else:
                        out["warnings"].append(f"rm -rf failed: {child.name}")
                except Exception as exc:
                    out["warnings"].append(f"docker rm {child.name}: {str(exc)[:80]}")
            except Exception as exc:
                out["warnings"].append(f"rmtree {child.name}: {str(exc)[:80]}")

    # Per-client DDL files
    for ddl_dir in [
        REPO_ROOT / "datalink" / "pipeline" / "bronze" / "ddl",
        REPO_ROOT / "datalink" / "pipeline" / "gold" / "ddl",
    ]:
        if not ddl_dir.exists():
            continue
        for p in ddl_dir.glob("*.sql"):
            # Keep the templates/_*.sql files
            if p.name.startswith("_"):
                continue
            try:
                p.unlink()
                out["counts"]["files"] += 1
            except Exception as exc:
                out["warnings"].append(f"unlink {p.name}: {str(exc)[:80]}")

    return out


# ---------------------------------------------------------------------------
# Airflow metadata wipe — reuse existing function
# ---------------------------------------------------------------------------


def _wipe_airflow(actor: str) -> dict:
    rpt = reset_airflow_metadata(dag_id=None, actor=actor)
    return {
        "counts": rpt.counts,
        "warnings": rpt.warnings,
        "errors": rpt.errors,
    }


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------


def wipe_everything(
    *,
    actor: str,
    include_standards: bool = False,
    include_airflow: bool = True,
    include_files: bool = True,
) -> WipeReport:
    """Wipe all workflow-driving data across Snowflake + Postgres + SQL Server.

    Demo lifecycle: call this between demos to start from a clean slate
    with zero datasets, zero designs, zero instances, zero DQ runs.

    Args:
        actor: who triggered (e.g. ``"admin:ui:jatin"``) — logged.
        include_standards: if True, also wipes the 6 industry-standards
            (FHIR/X12/NCPDP/CMS/DV2/HEDIS).  These take ~10 min to reload
            via Voyage so default is False.
        include_airflow: wipe Airflow metadata DB (task_instance / dag_run).
        include_files: remove auto-generated DAG factories + dbt + DDL files.
    """
    rpt = WipeReport(actor=actor, started_at=_now())

    # Snowflake — the main event
    rpt.sections["snowflake"] = _wipe_snowflake(actor=actor)

    # Standards opt-in
    if include_standards:
        try:
            _wh().execute(f"DELETE FROM {CONTROL_SCHEMA}.standard_chunks")
            _wh().execute(f"DELETE FROM {CONTROL_SCHEMA}.standard_registry")
            rpt.sections["snowflake"]["counts"]["tables"] += 2
            rpt.sections["snowflake"]["counts"]["standards_wiped"] = 1
        except Exception as exc:
            rpt.sections["snowflake"]["warnings"].append(f"standards wipe: {str(exc)[:120]}")

    # Postgres
    rpt.sections["postgres"] = _wipe_postgres(actor=actor)

    # SQL Server (warnings-only if container down)
    rpt.sections["sqlserver"] = _wipe_sqlserver(actor=actor)

    # Filesystem
    if include_files:
        rpt.sections["files"] = _wipe_generated_files(actor=actor)

    # Airflow
    if include_airflow:
        rpt.sections["airflow"] = _wipe_airflow(actor=actor)

    rpt.finished_at = _now()

    # Audit log — reuse the per-op pattern, log under a synthetic ResetReport
    try:
        from datalink.admin.reset import ResetReport

        synth = ResetReport(
            operation="wipe_everything",
            actor=actor,
            started_at=rpt.started_at,
            finished_at=rpt.finished_at,
            counts=rpt.total_counts(),
            warnings=[w for s in rpt.sections.values() for w in s.get("warnings", [])],
            errors=[e for s in rpt.sections.values() for e in s.get("errors", [])],
        )
        _log_audit(synth, None)
    except Exception as exc:
        _log.warning("wipe_everything.audit_log_failed", err=str(exc)[:200])

    # Final sweep: the audit-log itself was wiped during _wipe_snowflake,
    # but the helpers above (`reset_airflow_metadata` → `_log_audit` and our
    # own synthetic `_log_audit` call) each append a row.  For "from scratch
    # for team to comprehend" demos the operator wants a TRULY pristine
    # admin_reset_audit_log too — so we truncate AFTER all the audit writers
    # have run.  Cost: lose the in-this-call audit trail.  Worth it for
    # repeatable demo state.
    try:
        _wh().execute(f"DELETE FROM {CONTROL_SCHEMA}.admin_reset_audit_log")
    except Exception as exc:
        _log.warning("wipe_everything.final_audit_truncate_failed", err=str(exc)[:200])

    return rpt
