"""Provider pipeline DAG factory — auto-generated by
``scripts/regenerate_dag_factories.py`` (Phase 17.7).

Generates ONE Airflow DAG per LIVE row in
``CONTROL.client_pipeline_instances WHERE dataset_code='provider'``.
Per-client schedules + tier sizing flow through metadata, not code.

Adding a new client to Provider = INSERT a row in CONTROL — no edits
to this file. Removing a client = mark their instance ARCHIVED in
CONTROL — the corresponding DAG disappears on next scheduler reload.

DO NOT HAND-EDIT — re-run the regen script and override behaviour by
adding ``dags/overrides/provider.py`` (Phase 17.8 hook, optional).
"""

from __future__ import annotations

from _factory_common import (
    register_dags_for_dataset,
)

DATASET = "provider"

# Calling register_dags_for_dataset injects each generated DAG into this
# module's globals() — Airflow's DagBag picks them up automatically.
register_dags_for_dataset(DATASET, globals())
