-- AUTO-GENERATED by Data Contract Architect (Phase 14)
-- client     : aetna
-- source     : CLAIMS
-- generated  : 2026-04-30T21:36:44.345351+00:00
--
-- Starter Silver model. Extend with Data Vault hubs/sats/links
-- via Smart Mapper, or hand-roll your transformations here.

{{ config(
    materialized='view',
    schema='silver_aetna',
    tags=['contract_architect', 'aetna', 'claims']
) }}

select
  cast(claim_id as VARCHAR) as claim_id,
  cast(member_id as VARCHAR) as member_id,
  cast(provider_npi as VARCHAR) as provider_npi,
  cast(cpt_code as VARCHAR) as cpt_code,
  cast(icd10_primary as VARCHAR) as icd10_primary,
  _load_dt,
  _source_file,
  _batch_id,
  _record_source
from {{ source('bronze_aetna', 'raw_claims') }}
