-- Phase 15 Pipeline Architect — Gold dbt model
-- Source : SILVER___GLOBAL__.membership_clean
-- Target : GOLD___GLOBAL__.membership
-- Pattern: latest-per-business-key snapshot (UM_OPERATIONAL)

{{ config(
    materialized = 'table',
    cluster_by   = ['member_card_id', 'member_medicare_id', 'member_medicaid_id', 'attributed_provider_id']
) }}

WITH ranked AS (
    SELECT
        payer_name,
        member_card_id,
        member_medicare_id,
        member_medicaid_id,
        member_first_name,
        member_middle_name,
        member_last_name,
        member_gender,
        member_birth_date,
        member_phone,
        member_street_address_line1,
        member_street_address_line2,
        member_county_code,
        member_county_name,
        member_city,
        member_state,
        member_zip_code,
        member_active_status,
        member_relationship_code,
        member_medicaid_indicator,
        member_medicaid_dual_eligibility_indicator,
        member_dual_eligibility_begin_date,
        member_dual_eligibility_end_date,
        member_coverage_effective_date,
        member_coverage_end_date,
        member_provider_pcp_begin_date,
        member_health_plan_begin_date,
        member_enrollment_date,
        member_line_of_business,
        member_product,
        product_description,
        plan_benenfit_package_id,
        plan_benefit_package_name,
        segment_id_plan_benefit_package,
        member_product_begin_date,
        managed_care_organization_contract_number,
        attributed_provider_id,
        atrributed_provider_npi,
        attributed_provider_contract_id,
        plan_benefit_package_id,
        refresh_date,
        _load_dt,
        _batch_id,
        _record_source,
        _record_hash,
        ROW_NUMBER() OVER (
            PARTITION BY member_card_id, member_medicare_id, member_medicaid_id, attributed_provider_id
            ORDER BY _load_dt DESC, _record_hash DESC
        ) AS _rn
    FROM {{ source('silver___global__', 'membership_clean') }}
)
SELECT
    payer_name,
        member_card_id,
        member_medicare_id,
        member_medicaid_id,
        member_first_name,
        member_middle_name,
        member_last_name,
        member_gender,
        member_birth_date,
        member_phone,
        member_street_address_line1,
        member_street_address_line2,
        member_county_code,
        member_county_name,
        member_city,
        member_state,
        member_zip_code,
        member_active_status,
        member_relationship_code,
        member_medicaid_indicator,
        member_medicaid_dual_eligibility_indicator,
        member_dual_eligibility_begin_date,
        member_dual_eligibility_end_date,
        member_coverage_effective_date,
        member_coverage_end_date,
        member_provider_pcp_begin_date,
        member_health_plan_begin_date,
        member_enrollment_date,
        member_line_of_business,
        member_product,
        product_description,
        plan_benenfit_package_id,
        plan_benefit_package_name,
        segment_id_plan_benefit_package,
        member_product_begin_date,
        managed_care_organization_contract_number,
        attributed_provider_id,
        atrributed_provider_npi,
        attributed_provider_contract_id,
        plan_benefit_package_id,
        refresh_date,
    _load_dt,
    _batch_id,
    _record_source,
    _record_hash,
    _batch_id              AS _silver_run_id,
    CURRENT_TIMESTAMP()    AS _gold_effective_dt
FROM ranked
WHERE _rn = 1
