"""Regenerate per-dataset Airflow DAG factory files — Phase 17.10.

Default behaviour (instance-aware):
  Writes ``dags/_factory_<dataset>.py`` ONLY for datasets that have at
  least one non-archived row in CONTROL.client_pipeline_instances.
  Datasets without instances generate ZERO DAGs at scheduler load — so
  having a factory file for them is dead weight that just clutters the
  DAG bag.  Run ``scripts/cleanup_dags.py`` separately to remove stale
  factories.

Force-all mode (legacy / bootstrap):
  ``--all-datasets`` writes a factory for every Bronze catalog row,
  matching the original Phase-17.7 behaviour.

Idempotent — re-running won't change a factory whose content already
matches the canonical template, so it's safe to wire into the deploy
flow (approve_and_deploy auto-ensures a factory exists for each newly
deployed dataset).

USAGE
-----
    python scripts/regenerate_dag_factories.py                 # only datasets with instances
    python scripts/regenerate_dag_factories.py membership      # single dataset (always written)
    python scripts/regenerate_dag_factories.py --all-datasets  # legacy: write all 33
    python scripts/regenerate_dag_factories.py --dry-run       # show diff, write nothing

Without Snowflake creds the script falls back to scanning the local Bronze
catalog seed (``data/generated/*.psv``) so it can run in CI/dev offline.
"""

from __future__ import annotations

import argparse
import os
import sys
from pathlib import Path

# Resolve repo root regardless of where the script is launched from.
REPO_ROOT = Path(__file__).resolve().parent.parent
DAGS_DIR = REPO_ROOT / "dags"


# ---------------------------------------------------------------------------
# The canonical factory file template — kept identical to
# ``dags/_factory_membership.py`` (the hand-authored Phase 17.3 reference)
# so all 33 factories are byte-for-byte consistent.
# ---------------------------------------------------------------------------
FACTORY_TEMPLATE = '''"""{display_name} pipeline DAG factory — auto-generated by
``scripts/regenerate_dag_factories.py`` (Phase 17.7).

Generates ONE Airflow DAG per LIVE row in
``CONTROL.client_pipeline_instances WHERE dataset_code='{dataset_code}'``.
Per-client schedules + tier sizing flow through metadata, not code.

Adding a new client to {display_name} = INSERT a row in CONTROL — no edits
to this file. Removing a client = mark their instance ARCHIVED in
CONTROL — the corresponding DAG disappears on next scheduler reload.

DO NOT HAND-EDIT — re-run the regen script and override behaviour by
adding ``dags/overrides/{dataset_code}.py`` (Phase 17.8 hook, optional).
"""

from __future__ import annotations

from _factory_common import register_dags_for_dataset  # noqa: E402  (Airflow adds dags_folder to sys.path)

DATASET = "{dataset_code}"

# Calling register_dags_for_dataset injects each generated DAG into this
# module's globals() — Airflow's DagBag picks them up automatically.
register_dags_for_dataset(DATASET, globals())
'''


# ---------------------------------------------------------------------------
# Dataset list resolution — Snowflake → fallback to local PSV scan.
# ---------------------------------------------------------------------------
def _list_datasets_from_snowflake() -> list[tuple[str, str]] | None:
    """Returns [(dataset_code, display_name)] or None on any failure."""
    try:
        import snowflake.connector
    except ImportError:
        return None
    try:
        conn = snowflake.connector.connect(
            account=os.environ["SNOWFLAKE_ACCOUNT"],
            user=os.environ["SNOWFLAKE_USER"],
            password=os.environ["SNOWFLAKE_PASSWORD"],
            role=os.environ.get("SNOWFLAKE_ROLE", "ACCOUNTADMIN"),
            warehouse=os.environ.get("SNOWFLAKE_WAREHOUSE", "COMPUTE_WH"),
            database=os.environ.get("SNOWFLAKE_DATABASE", "DATALINK_DEV"),
        )
    except Exception as exc:
        print(f"  (snowflake connect failed: {exc!s}; trying local fallback)", file=sys.stderr)
        return None
    try:
        cur = conn.cursor()
        cur.execute(
            "SELECT dataset_code, display_name "
            "FROM CONTROL.global_bronze_catalog_datasets "
            "ORDER BY dataset_code"
        )
        rows = [(r[0], r[1]) for r in cur.fetchall()]
        cur.close()
        conn.close()
        return rows
    except Exception as exc:
        print(f"  (snowflake query failed: {exc!s}; trying local fallback)", file=sys.stderr)
        try:
            conn.close()
        except Exception:
            pass
        return None


def _list_datasets_from_local() -> list[tuple[str, str]]:
    """Offline fallback: scan ``data/generated/*_bronze_sample.psv`` filenames."""
    gen = REPO_ROOT / "data" / "generated"
    if not gen.exists():
        return []
    out: list[tuple[str, str]] = []
    for p in sorted(gen.glob("*_bronze_sample.psv")):
        code = p.stem.replace("_bronze_sample", "")
        out.append((code, code.replace("_", " ").title()))
    return out


def list_datasets() -> list[tuple[str, str]]:
    rows = _list_datasets_from_snowflake()
    if rows is None:
        print("  (using local PSV scan fallback)", file=sys.stderr)
        rows = _list_datasets_from_local()
    return rows


# ---------------------------------------------------------------------------
# Render + write
# ---------------------------------------------------------------------------
def render(dataset_code: str, display_name: str) -> str:
    return FACTORY_TEMPLATE.format(dataset_code=dataset_code, display_name=display_name)


def write_factory(dataset_code: str, display_name: str, *, dry_run: bool = False) -> str:
    """Write dags/_factory_<dataset_code>.py if content differs.

    Returns one of: 'created', 'updated', 'unchanged', 'skipped-dryrun'.
    """
    target = DAGS_DIR / f"_factory_{dataset_code}.py"
    new_text = render(dataset_code, display_name)
    if target.exists():
        old_text = target.read_text()
        if old_text == new_text:
            return "unchanged"
        if dry_run:
            return "skipped-dryrun"
        target.write_text(new_text)
        return "updated"
    if dry_run:
        return "skipped-dryrun"
    DAGS_DIR.mkdir(parents=True, exist_ok=True)
    target.write_text(new_text)
    return "created"


def _list_datasets_with_instances() -> set[str] | None:
    """Return dataset_codes that have at least one non-archived instance.
    None if Snowflake is unreachable (caller decides fallback)."""
    try:
        import snowflake.connector
    except ImportError:
        return None
    try:
        conn = snowflake.connector.connect(
            account=os.environ["SNOWFLAKE_ACCOUNT"],
            user=os.environ["SNOWFLAKE_USER"],
            password=os.environ["SNOWFLAKE_PASSWORD"],
            role=os.environ.get("SNOWFLAKE_ROLE", "ACCOUNTADMIN"),
            warehouse=os.environ.get("SNOWFLAKE_WAREHOUSE", "COMPUTE_WH"),
            database=os.environ.get("SNOWFLAKE_DATABASE", "DATALINK_DEV"),
        )
    except Exception:
        return None
    try:
        cur = conn.cursor()
        cur.execute(
            "SELECT DISTINCT LOWER(dataset_code) "
            "FROM CONTROL.client_pipeline_instances "
            "WHERE status <> 'ARCHIVED'"
        )
        return {r[0] for r in cur.fetchall() if r[0]}
    except Exception:
        return None
    finally:
        try:
            cur.close()
            conn.close()
        except Exception:
            pass


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "dataset",
        nargs="?",
        help="Single dataset_code to regenerate (always written, even with no instances)",
    )
    parser.add_argument(
        "--all-datasets",
        action="store_true",
        help="Write a factory for EVERY Bronze catalog dataset (legacy 17.7 mode). "
        "Default is instance-aware: only datasets with active instances get a factory.",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Print actions without writing files",
    )
    args = parser.parse_args()

    rows = list_datasets()
    if not rows:
        print("ERROR: no datasets found (Snowflake unreachable AND no local PSVs)", file=sys.stderr)
        return 2

    if args.dataset:
        rows = [(c, d) for c, d in rows if c == args.dataset]
        if not rows:
            print(f"ERROR: dataset_code {args.dataset!r} not in catalog", file=sys.stderr)
            return 2
    elif not args.all_datasets:
        # Instance-aware (default): only datasets with active instances.
        active = _list_datasets_with_instances()
        if active is None:
            print(
                "  (could not resolve active datasets — falling back to "
                "all-datasets mode; pass --all-datasets to silence)",
                file=sys.stderr,
            )
        else:
            before = len(rows)
            rows = [(c, d) for c, d in rows if c in active]
            print(
                f"  (instance-aware: {before} datasets in catalog → "
                f"{len(rows)} have active instances)",
                file=sys.stderr,
            )
            if not rows:
                print(
                    "No datasets with active instances. Nothing to write. "
                    "(Use --all-datasets to bootstrap all 33 factories.)"
                )
                return 0

    summary = {"created": 0, "updated": 0, "unchanged": 0, "skipped-dryrun": 0}
    for code, display in rows:
        action = write_factory(code, display, dry_run=args.dry_run)
        summary[action] = summary.get(action, 0) + 1
        marker = {
            "created": "+",
            "updated": "~",
            "unchanged": " ",
            "skipped-dryrun": "?",
        }[action]
        print(f"  {marker} _factory_{code}.py")

    print(
        f"\nSummary: {summary['created']} created, "
        f"{summary['updated']} updated, "
        f"{summary['unchanged']} unchanged"
        + (f", {summary['skipped-dryrun']} skipped (dry-run)" if args.dry_run else "")
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
