-- AUTO-GENERATED by Pipeline Architect (Phase 15)
-- Gold DDL for aetna / provider
-- instance_id : df4b104b-7f8e-482c-ac9a-310065a3df4c
-- generated   : 2026-05-10T00:20:16.101766+00:00
-- DO NOT EDIT BY HAND. Re-deploy from the UI to regenerate.

-- Phase 15 Pipeline Architect — Gold table for aetna / provider
-- Generated from CONTROL.global_bronze_catalog_fields (catalog_version=1)
-- Generated at: 2026-05-10T00:19:47.978188+00:00
CREATE TABLE IF NOT EXISTS GOLD_AETNA.provider (
    -- ── Gold business columns ──
    national_provider_identifier_npi   VARCHAR        NULL,  -- National Provider Identifier (NPI) — [PHI]
    provider_identification_number_id  VARCHAR        NULL,  -- Provider Identification Number(ID)
    provider_first_name                VARCHAR        NULL,  -- Provider First Name — [PII]
    provider_middle_name               VARCHAR        NULL,  -- Provider Middle Name — [PII]
    provider_last_name                 VARCHAR        NULL,  -- Provider Last Name — [PII]
    provider_tax_id                    VARCHAR        NULL,  -- Provider Tax ID — [PII]
    provider_tax_id_name               VARCHAR        NULL,  -- Provider Tax ID Name — [PII] — [PHI]
    provider_primary_servicing_address_line_1 VARCHAR        NULL,  -- Provider Primary Servicing Address Line 1 — [PII]
    provider_primary_servicing_address_line_2 VARCHAR        NULL,  -- Provider Primary Servicing Address Line 2 — [PII]
    provider_primary_servicing_address_city VARCHAR        NULL,  -- Provider Primary Servicing Address City — [PII]
    provider_primary_servicing_address_state VARCHAR        NULL,  -- Provider Primary Servicing Address State — [PII]
    provider_primary_servicing_address_zip_code VARCHAR        NULL,  -- Provider Primary Servicing Address Zip Code — [PII]
    provider_contracted_entity_name    VARCHAR        NULL,  -- Provider Contracted Entity Name — [PII]
    refresh_date                       DATE           NULL,  -- Refresh Date
    -- ── DataLink Gold audit columns (auto-injected) ──
    _load_dt                           TIMESTAMP      NULL,
    _batch_id                          VARCHAR        NULL,
    _record_source                     VARCHAR        NULL,
    _record_hash                       VARCHAR        NULL,
    _silver_run_id                     VARCHAR        NULL,
    _gold_effective_dt                 TIMESTAMP      NULL
);
