-- AUTO-GENERATED by Pipeline Architect (Phase 15)
-- Gold DDL for aetna / membership
-- instance_id : 6d296c91-e2a6-4ea7-b306-422db85697cd
-- generated   : 2026-05-10T00:19:17.980143+00:00
-- DO NOT EDIT BY HAND. Re-deploy from the UI to regenerate.

-- Phase 15 Pipeline Architect — Gold table for aetna / membership
-- Generated from CONTROL.global_bronze_catalog_fields (catalog_version=1)
-- Generated at: 2026-05-10T00:17:16.474384+00:00
CREATE TABLE IF NOT EXISTS GOLD_AETNA.membership (
    -- ── Gold business columns ──
    payer_name                         VARCHAR        NULL,  -- Payer Name — [PII]
    member_card_id                     VARCHAR        NOT NULL,  -- Member Card ID — [BUSINESS_KEY]
    member_medicare_id                 VARCHAR        NOT NULL,  -- Member Medicare ID — [PHI] — [BUSINESS_KEY]
    member_medicaid_id                 VARCHAR        NOT NULL,  -- Member Medicaid ID — [PHI] — [BUSINESS_KEY]
    member_first_name                  VARCHAR        NULL,  -- Member First Name — [PII]
    member_middle_name                 VARCHAR        NULL,  -- Member Middle Name — [PII]
    member_last_name                   VARCHAR        NULL,  -- Member Last Name — [PII]
    member_gender                      VARCHAR        NULL,  -- Member Gender
    member_birth_date                  DATE           NULL,  -- Member Birth Date — [PII]
    member_phone                       VARCHAR        NULL,  -- Member Phone — [PII]
    member_street_address_line1        VARCHAR        NULL,  -- Member Street Address Line1 — [PII]
    member_street_address_line2        VARCHAR        NULL,  -- Member Street Address Line2 — [PII]
    member_county_code                 VARCHAR        NULL,  -- Member County Code — [PII]
    member_county_name                 VARCHAR        NULL,  -- Member County Name — [PII]
    member_city                        VARCHAR        NULL,  -- Member City — [PII]
    member_state                       VARCHAR        NULL,  -- Member State — [PII]
    member_zip_code                    VARCHAR        NULL,  -- Member ZIP Code — [PII]
    member_active_status               VARCHAR        NULL,  -- Member Active Status
    member_relationship_code           VARCHAR        NULL,  -- Member Relationship Code
    member_medicaid_indicator          BOOLEAN        NULL,  -- Member Medicaid Indicator — [PHI]
    member_medicaid_dual_eligibility_indicator BOOLEAN        NULL,  -- Member Medicaid Dual Eligibility Indicator — [PHI]
    member_dual_eligibility_begin_date DATE           NULL,  -- Member Dual Eligibility Begin Date
    member_dual_eligibility_end_date   DATE           NULL,  -- Member Dual Eligibility End Date
    member_coverage_effective_date     DATE           NULL,  -- Member Coverage Effective Date — [PHI]
    member_coverage_end_date           DATE           NULL,  -- Member Coverage End Date — [PHI]
    member_provider_pcp_begin_date     DATE           NULL,  -- Member Provider(PCP) Begin Date
    member_health_plan_begin_date      DATE           NULL,  -- Member Health Plan Begin Date — [PHI]
    member_enrollment_date             DATE           NULL,  -- Member Enrollment Date
    member_line_of_business            VARCHAR        NULL,  -- Member Line Of  Business
    member_product                     VARCHAR        NULL,  -- Member Product
    product_description                VARCHAR        NULL,  -- Product Description
    plan_benenfit_package_id           INTEGER        NULL,  -- Plan Benenfit Package ID — [PHI]
    plan_benefit_package_name          VARCHAR        NULL,  -- Plan Benefit Package Name — [PII] — [PHI]
    segment_id_plan_benefit_package    INTEGER        NULL,  -- Segment ID - Plan Benefit Package — [PHI]
    member_product_begin_date          DATE           NULL,  -- Member Product Begin Date
    managed_care_organization_contract_number VARCHAR        NULL,  -- Managed Care Organization Contract Number — [PHI]
    attributed_provider_id             VARCHAR        NOT NULL,  -- Attributed Provider ID — [PHI] — [BUSINESS_KEY]
    atrributed_provider_npi            VARCHAR        NULL,  -- Atrributed Provider NPI — [PHI]
    attributed_provider_contract_id    DECIMAL(20, 4) NULL,  -- Attributed Provider Contract ID
    plan_benefit_package_id            VARCHAR        NULL,  -- Plan Benefit Package ID — [PHI]
    refresh_date                       DATE           NULL,  -- Refresh Date
    -- ── DataLink Gold audit columns (auto-injected) ──
    _load_dt                           TIMESTAMP      NULL,
    _batch_id                          VARCHAR        NULL,
    _record_source                     VARCHAR        NULL,
    _record_hash                       VARCHAR        NULL,
    _silver_run_id                     VARCHAR        NULL,
    _gold_effective_dt                 TIMESTAMP      NULL
);
